### ISSUE TITLE
MPV master fails on loadfile command

### ISSUE THREAD

**Issue by odrling** [DakaraProject/dakara-player#121]
Tests (and regular use) fail since https://github.com/mpv-player/mpv/commit/c678033c1d60b48ae02fbbe4815869b9504a17f6

https://hikari.butaishoujo.moe/t/ab9bddc9/tests.log (updated because I had unrelated tests failures)

**Comment by Neraste** [comment]
Great, another version-specific backend is needed. Let's see if we can avoid this.
