### ISSUE TITLE
VLC window closes on Windows

### ISSUE THREAD

**Issue by Neraste** [DakaraProject/dakara-player#15]

**Comment by Neraste** [comment]
Maybe try playlist objects?

**Comment by Nadeflore** [comment]
Using media_list seams to solve the issue.

Here is the code that was used under windows, and plays several videos without closing the windows between videos:

```python
import vlc

instance = vlc.Instance()

player = instance.media_player_new()
media_list = instance.media_list_new()
list_player = instance.media_list_player_new()
list_player.set_media_list(media_list)
list_player.set_media_player(player)

media = instance.media_new_path(r"C:\file1.mkv")
media2 = instance.media_new_path(r"C:\file2.mkv")

media_list.add_media(media)
media_list.add_media(media2)

list_player.play()

input()

player.set_position(0.99)

input()
```

**Comment by Neraste** [comment]
Sheez, so this is the day we have to move to media list…

**Comment by Neraste** [comment]
Another solution would be to create a window and request VLC to use it. See `set_hwnd` in the [doc](https://www.olivieraubert.net/vlc/python-ctypes/doc/). See this [code example](https://python-catalin.blogspot.com/2017/09/the-python-vlc-python-module.html) where they use pygame to create the window.
